// resendOtpActionTypes.js
export const RESEND_ADMIN_OTP_REQUEST = "RESEND_ADMIN_OTP_REQUEST";
export const RESEND_ADMIN_OTP_SUCCESS = "RESEND_ADMIN_OTP_SUCCESS";
export const RESEND_ADMIN_OTP_FAILURE = "RESEND_ADMIN_OTP_FAILURE";
