// actionTypes.js

export const UPLOAD_MALE_IMAGES_REQUEST = "UPLOAD_MALE_IMAGES_REQUEST";
export const UPLOAD_MALE_IMAGES_SUCCESS = "UPLOAD_MALE_IMAGES_SUCCESS";
export const UPLOAD_MALE_IMAGES_FAILURE = "UPLOAD_MALE_IMAGES_FAILURE";

export const UPLOAD_FEMALE_IMAGES_REQUEST = "UPLOAD_FEMALE_IMAGES_REQUEST";
export const UPLOAD_FEMALE_IMAGES_SUCCESS = "UPLOAD_FEMALE_IMAGES_SUCCESS";
export const UPLOAD_FEMALE_IMAGES_FAILURE = "UPLOAD_FEMALE_IMAGES_FAILURE";

export const UPLOAD_OTHER_IMAGES_REQUEST = "UPLOAD_OTHER_IMAGES_REQUEST";
export const UPLOAD_OTHER_IMAGES_SUCCESS = "UPLOAD_OTHER_IMAGES_SUCCESS";
export const UPLOAD_OTHER_IMAGES_FAILURE = "UPLOAD_OTHER_IMAGES_FAILURE";

export const GET_ALL_IMAGES_REQUEST = "GET_ALL_IMAGES_REQUEST";
export const GET_ALL_IMAGES_SUCCESS = "GET_ALL_IMAGES_SUCCESS";
export const GET_ALL_IMAGES_FAILURE = "GET_ALL_IMAGES_FAILURE";
